version: '3.4'

services:
  api-corachan:
    build: ./corachan
    volumes:
      - ./corachan:/usr/src/app
    ports:
      - 5000:80
  api-pilar:
    build: ./pilar
    volumes:
      - ./pilar:/usr/src/app
    ports:
      - 5001:80
  api-teknon:
    build: ./teknon
    volumes:
      - ./teknon:/usr/src/app
    ports:
      - 5002:80

